Repository stolostron/search-v2-api, pull requests merged in 2022-01, with the labels that each got.

#3 Onboard to prow
  Dockerfile.prow
  Makefile.prow
  OWNERS
Labels: lgtm

#4 Refactor Search resolver
  Makefile
  go.mod
  go.sum
  gqlgen.yml
  graph/generated/generated.go
  graph/model/models_gen.go
  graph/schema.resolvers.go
  pkg/resolver/related.go
  pkg/resolver/search.go
  pkg/resolver/search_test.go
  tools.go
Labels: lgtm, approved

#5 Update project references to stolostron
  Dockerfile
  Dockerfile.prow
  go.mod
  gqlgen.yml
  graph/generated/generated.go
  graph/schema.resolvers.go
  main.go
  pkg/database/connection.go
  pkg/resolver/related.go
  pkg/resolver/search.go
  pkg/resolver/search_test.go
  pkg/schema/searchComplete.go
  pkg/schema/searchSchema.go
  pkg/server/server.go
Labels: lgtm, approved

#7 Add schema to table names
  pkg/resolver/related.go
  pkg/resolver/search.go
  pkg/resolver/search_test.go
  pkg/schema/searchComplete.go
  pkg/schema/searchSchema.go
Labels: lgtm, approved

#8 Update Prow
  COMPONENT_NAME
  Makefile
  Makefile.prow
  go.mod
  go.sum
  sonar-project.properties
Labels: lgtm, approved

#6 Add rebuild date to readme
  README.md
Labels: lgtm, approved

#9 Merge relationships PR
  Makefile
  Makefile.prow
  graph/generated/generated.go
  graph/schema.resolvers.go
  pkg/resolver/related.go
  pkg/resolver/search.go
Labels: lgtm, approved

#13 Initial test for search Items() resolver
  pkg/database/connection.go
  pkg/resolver/mocks/mock.json
  pkg/resolver/related.go
  pkg/resolver/search.go
  pkg/resolver/search_test.go
  pkg/resolver/testHelper_test.go
Labels: lgtm, approved, dco-signoff: yes
